[package]
name = "locators"
description = "Human exchangable identifiers and locators"
version = "0.4.0"
edition = "2021"
authors = ["Andrew Cowie"]
license = "MIT"
repository = "https://github.com/aesiniath/locators-rust"

[dependencies]
base62 = "2.2"

[dev-dependencies]
quickcheck = "1.0"
